### ISSUE TITLE
Model animations

### ISSUE THREAD

**Issue by damiansk** [swift502/Sketchbook#19]
Hi, at a first, great job with this project. This source code is better than most of the available tutorials about web game development with Three.js and Cannon.js.
I want to ask you if you could describe, how did you prepare a single `*.fbx` file which contains both the 3d model and animations?

**Comment by swift502** [comment]
Hi,

Sorry for a late response. It's pretty simple. I attach all the animation actions I want to export to the skeleton in the NLA editor.

![image](https://user-images.githubusercontent.com/24359130/77235059-05de6380-6bb3-11ea-9fc9-860755927039.png)

Then when exporting to FBX, uncheck all actions, and check NLA strips to only export the actions you want.

![image](https://user-images.githubusercontent.com/24359130/77235062-0aa31780-6bb3-11ea-8ee4-e59521394267.png)

I'm using GLTF nowadays, but the process is pretty much identical.

**Comment by damiansk** [comment]
Indeed it's looks simple, I will try this approach with GLTF file to attach Miaxamo animations to single 3d model. Thanks a lot!
