### ISSUE TITLE
Character physics stuck in box 

### ISSUE THREAD

**Issue by raoneel** [swift502/Sketchbook#21]
I've noticed that the character can get stuck if it jumps directly into a box physics collider. It basically sticks to the box and stays in the falling animation. You can leave by turning around however. Is there any way to make it so that it bounces off instead?

![Screen Shot 2020-04-24 at 12 35 31 PM](https://user-images.githubusercontent.com/1142156/80250171-25403480-8628-11ea-8557-6dd571593f54.png)

**Comment by swift502** [comment]
That didn't happen in my demos.

What are your friction values? I think it should be 0.3 on the environment
https://github.com/swift502/Sketchbook/blob/fdb0b9f459fa4c14618ad50b48770f7010a19d41/src/ts/objects/object_physics/BoxPhysics.ts#L18

and 0.1 or even 0 on the player capsule
https://github.com/swift502/Sketchbook/blob/fdb0b9f459fa4c14618ad50b48770f7010a19d41/src/ts/characters/Character.ts#L137

Try setting the second one to 0 and it should definitely work. If not then I don't know why it happens to you.

**Comment by raoneel** [comment]
Setting the character friction to 0 seems to work well, thanks!
