### ISSUE TITLE
Blender glb model issue

### ISSUE THREAD

**Issue by vujadin** [swift502/Sketchbook#22]
What export settings are you using when exporting glb from Blender ?
When I use your car glb model and re-export it from Blender, physics is messed up.

![sberror](https://user-images.githubusercontent.com/4639385/80314830-32aa1a00-87f4-11ea-9ae0-7a034a7fe994.jpg)

**Comment by swift502** [comment]
I think this should work.
If physics don't work, it's likely because "custom properties" weren't exported. I'd say make sure to check that setting.
![](https://user-images.githubusercontent.com/24359130/73779949-da7ff080-478d-11ea-9d3d-f5dfa96fb3c7.png)

**Comment by vujadin** [comment]
I was actually exporting "custom properties". I've tried exactly the same settings as yours but the issue remains. It looks like colliding objects of a car are rotated in a wrong way. I can enter the car and turn the wheels, but the car is floating up in the air and the players is rotated incorrectly.
![sberror](https://user-images.githubusercontent.com/4639385/80317810-38a8f680-8806-11ea-8d45-b2e7ba47f9b9.jpg)

![expsett](https://user-images.githubusercontent.com/4639385/80317898-c97fd200-8806-11ea-89be-b9e89ade7f6a.jpg)

**Comment by vujadin** [comment]
Solved the issue by using Blender 2.83 Beta (was using 2.82a).
