### ISSUE TITLE
maps

### ISSUE THREAD

**Issue by Hoodgail** [swift502/Sketchbook#23]
have u thought on work on a map editor?

**Comment by swift502** [comment]
I used Blender to build my maps, which is very convenient. It is basically a map editor on it's own. I'd be more keen on making a Blender plugin which would let you tag objects with Sketchbook specific properties.

Here's a picture of Gabe Newell to improve your day. 👌
![58f7686e84b713aab61d0a08](https://user-images.githubusercontent.com/24359130/82655404-6c6b1680-9c22-11ea-87c7-018791425c0e.png)

Sorry for a late reply btw.

**Comment by Hoodgail** [comment]
kk
