### ISSUE TITLE
features

### ISSUE THREAD

**Issue by Hoodgail** [swift502/Sketchbook#24]
have u thought of adding 
- obstacles for the player to hold such as ``guns`` ``knife`` ``etc``
- first person view
- health
- fall damage
- an AO shader ( PLEASE NOT ~~SSAO~~ ) one dat dont make u get ``-100 fps``
- ur using the sky shader... make it change depending on ur time for EX ``if its night where u are make it night in the game else day``
- wall run
- adding more characters to choose from
- make bots able to drive helicopters, cars etc (UR A FUCKING **GENIUS** im sure u can pull this off)
- use the bloom shader to add an option to disable it or else, and add sum emissive to the current map, sum lights and not just base textures
- a discord server 

# ill tell u if i got more thank u

**Comment by swift502** [comment]
😄  ok

First of all, I hope you're aware that I'm not working on this project, that it's shelved indefinitely.
I also hope you know that I ran [github projects](https://github.com/swift502/Sketchbook/projects) where I wrote out all the plans for my project. Anything that's not in there, I didn't intend adding.

But I can still answer your questions:

- **obstacles for the player to hold such as guns knife etc** - you mean weapons, not obstacles? weapons require bunch of extra animations and systems, I started working on it in a different private branch of the project but didn't get very far. ([video](https://www.youtube.com/watch?v=tXHcLxSaoOI))
- **first person view** - not something I'm personally interested in. I was really interested in how third person character controls work and solving the challenges tied to third person character controls. I'd welcome a contribution that adds a first person controls mode, but it'd have to be a really clean and well integrated solution respecting the rest of the existing systems, not just a quick addon.
- **health** - it'd be trivial
- **fall damage** - it'd be trivial
- **an AO shader** - I did plan on adding AO. Something like a low sample double pass SSAO. Optional of course. I dislike SSAO as well, I think it looks pretty bad, but I can't imagine a better solution for a threejs based project. AFAIK it's still the least expensive solution out of all real-time AO solutions. And either way, I don't much care for performance in this project, as this isn't a real game, more of a sandbox project for cool experiments. And for every feature like this I usually add a checkbox to turn it off. By the way the ocean shader is probably the most expensive thing in the project by a long margin, I'd guess even more expensive than a potential SSAO effect.
- **day/night cycle** it'd be trivial. it'd require tweaking the lighting to change at night, but that's easy.
- **wall run** - I haven't thought of that. I'd love to try that in another project maybe, where it's just first person character controls. A mirror's edge style game perhaps.
- **more characters** - yeah, I spent like two years perfecting working a group of 6 characters, but I never finished any of them, here's a wip.

![image](https://user-images.githubusercontent.com/24359130/82703530-59813200-9c74-11ea-971f-e22594ceff51.png)

I didn't have any animations for the characters though. That'd be another aspect of it, making new animations for the specific characters.

- **make bots able to drive helicopters, cars etc** - they can already drive cars ([video](https://www.youtube.com/watch?v=8SUZxeGRBiA)). bots can already get into any vehicle, they can use the same things player can. They just have no goals, nowhere to drive or fly. You'd have to write behaviours to tell them what to do, which again, I think, isn't terribly difficult.
- **use the bloom shader** - I don't like bloom that much honestly. 🙂 I like clear visuals. But adding it would be pretty easy probably. I already have a compositing pipeline setup in three.js
- **a discord server** - I mean, I can create one, but there's probably gonna be like 2 people, me and you, at most.

# Thank you for your questions very much

Let me know if you manage to make something cool with the project. I'll even merge your changes into the main project if you wanted to.
I miss working on this. Let's just say I've got more important things to work on right now. Hopefully I'll come back to this some day.

**Comment by swift502** [comment]
![gaben](https://user-images.githubusercontent.com/24359130/82706040-18d7e780-9c79-11ea-8dc1-2b9c57286f0b.png)

**Comment by Hoodgail** [comment]
Thank you so much, dats the perfect answer i wanted.
 ❤️

**Comment by PLesiu6** [comment]
So when we should ask for link ?

**Comment by swift502** [comment]
@PLesiu6 Link to what?

**Comment by PLesiu6** [comment]
Link to discord server

**Comment by swift502** [comment]
@Hoodgail @PLesiu6 I made a discord server, not sure what we'll use it for (I'd like to keep issues and help questions here on Github), but it's there. Only took me 2 months.

I added a badge to the readme. Here's the invite: https://discord.com/invite/kRjrd4b

**Comment by Hoodgail** [comment]
May i possibly get a new invite? my old discord account was terminated

**Comment by swift502** [comment]
@Hoodgail https://discord.com/invite/fGuEqCe 👌

**Comment by swift502** [comment]
Test

**Comment by Hoodgail** [comment]
That was fast, thank you
