### ISSUE TITLE
webpack dev server

### ISSUE THREAD

**Issue by radziksh** [swift502/Sketchbook#3]
for now I use https://www.npmjs.com/package/http-server to start `examples/characters.html`. Maybe it makes sense to add `dev` script in package.json which will run https://github.com/webpack/webpack-dev-server?

**Comment by swift502** [comment]
If it has the same function then definitely yes. I remember I tried using it but wasn't successful, so I just kept using http-server.

You can make a pull request on the [dev](https://github.com/swift502/Sketchbook/tree/dev) branch if you want. Or I can just add it to the [0.3 project](https://github.com/swift502/Sketchbook/projects/5), I'll get to work on Sketchbook in a few months again, once the graphics for it are done.

**Comment by swift502** [comment]
In the next release. 👌
