### ISSUE TITLE
Link to blender source files seems glitchy

### ISSUE THREAD

**Issue by Houski** [swift502/Sketchbook#36]
When I try to get the blender files specified in the readme.md it seems as though that Google drive has issues.

This link. Anyone else having issues? Google is complaining it doesn't have an owner, can't download the files.

https://drive.google.com/drive/folders/1ZbziXLAW3yAn3e_s-6UO6jMIJWaglqDG?usp=sharing

**Comment by swift502** [comment]
Ok maybe google updated the link format... How about this?
 https://drive.google.com/folderview?id=1ZbziXLAW3yAn3e_s-6UO6jMIJWaglqDG
