### ISSUE TITLE
Multiple cameras and points of view.

### ISSUE THREAD

**Issue by eachtime** [swift502/Sketchbook#37]
Hello everyone, first of all I want to thank you for all this amazing work. It is quite impressive!

I saw that you are planning to implement a kind of GTA-like follow camera. I gave it a try my self, I'm not there yet at all, but maybe it's worth taking a look at my code.
I implemented it very naively but the result looks surprisingly good to me (I'm certainly not as exigent as you guys).

I have to make a few caveats though, I'm a little bit comfortable with JavaScript, but this is my first time with Typescript. I'm also not very good at maths or geometry.
I read a few articles and saw a couple of videos on quaternions, three.js cameras and stuff, but this was more of a trial and error implementation, so it could
hurt your eyes really bad.

Anyway, I would be glade to share my modifications and have some feedbacks. I created a new branch called cameras.
Correct me if I'm wrong, but according to the GitHub documentation, I think that you have to create the same one in order for me to do a pull request.
Or I can share it by any other means that is convenient for you.
I can also put an instance on my server if you want to try it first to decide if it's worth it for you to take a look at the code.

**Comment by swift502** [comment]
Hi!

Awesome. I'd definitely be interesting in checking out your changes and possibly merging them if we both like the final implementation.

You could've already made a pull request. https://docs.github.com/en/github/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-a-pull-request
You can request pulls across different branches as well.

And you don't have to put an instance on your server (unless you want to). Just link me the repo (or better yet, create the pull request), I can build it and test it myself. I checked your profile but you seem to have no public repositories?

**Comment by eachtime** [comment]
> We can discuss your implementation and other details directly in the PR thread.

So it means I should close this issue ?

**Comment by swift502** [comment]
I'll do it. 👍
