### ISSUE TITLE
Odd bug after fork and clone

### ISSUE THREAD

**Issue by Scottss** [swift502/Sketchbook#4]
After forking and cloning the project I loaded it up and I am having an issue with the players looking at a specific location on the ground. if they are in the air they float around and look like they are flying.

![image](https://user-images.githubusercontent.com/4674727/54502696-04bc8b80-48fa-11e9-8535-837be361d247.png)

**Comment by Scottss** [comment]
I recloned and it fixed it.

**Comment by swift502** [comment]
Could this have something to do with the version of three.js?
I know the newest version results in something similar and I'm certainly planning to fix _that_ issue.
