### ISSUE TITLE
Port demos to TypeScript

### ISSUE THREAD

**Issue by StanislavChankov** [swift502/Sketchbook#42]
Can you **please** provide source code that ports Sketchbook latest demo - https://jblaha.art/sketchbook/0.4/ to TypeScript?

**Comment by swift502** [comment]
I'm afraid someone more experienced with TypeScript will have to tackle this. I just tried to make a sample TS project but got stuck on compiling it. And importing sketchbook through a TS module gives me MIME errors. But I generally have no idea how TypeScript development works. I understand that the way Sketchbook is setup now using just Webpack is in itself unusual. And I don't know what the "usual" way is.

Maybe it's possible that just tweaking the Webpack configs will get us somewhere? What is your project setup? Did you get any specific error messages?

It's somewhat ironic but I don't feel qualified to fix this. I know the syntax of TypeScript but I always found that actually using it is very confusing and strangely convoluted.

**Comment by swift502** [comment]
I've removed the NPM usage section from readme. Unless someone can provide a working example of NPM usage, I don't know that it's possible to use it that way right now.

**Comment by StanislavChankov** [comment]
Aham, so you are saying that the TypeScript npm package is not working as the min.js version of the library?
If that's the case I think I can invest some time in TypeScript package.

**Comment by swift502** [comment]
I think we're misunderstanding each other. Lets resolve this on Discord.
