### ISSUE TITLE
How to first-person?

### ISSUE THREAD

**Issue by ghost** [swift502/Sketchbook#5]
How to do management from the first person

**Comment by swift502** [comment]
Hi!

Sorry for a late response. First person isn't currently on any of my [TODO lists](https://github.com/swift502/Sketchbook/projects). I'm personally really interested in the third person mode and how that's done.

The simple way of doing it is probably to create a first person [game mode](https://github.com/swift502/Sketchbook/blob/master/src/js/sketchbook/GameModes.js), then appropriate first person [character states](https://github.com/swift502/Sketchbook/blob/master/src/js/characters/CharacterStates.js) and a [character update](https://github.com/swift502/Sketchbook/blob/b6c2e0655e71f9ce6124e82d5d133960ff7f6441/src/js/characters/Character.js#L272) override. But there would be no support for a view-model of a weapon for instance, so you're still very limited in what you can do...

The thing is, taking my current character class and turning it first person like this would mean you're throwing away 90% of the class' functionality. It might as well be easier and more elegant to start from scratch and create a new character class that does exactly what you need, and only borrow the raycasting bit from my class, and throw out all of my character model and animation management, which you won't need in first person.

Like I said I'm not planning to do it currently. But I guess if enough people wanted it I'd consider it. Sorry.

Thank you for being interested In sketchbook though. It's just a simple playground of mine, and can't do much now. I plan to start working on it in a few months again...

**Comment by aleqsu** [comment]
Thanks for the answer, I will continue to follow your wonderful project)
