### ISSUE TITLE
Extreme FPS slowdown?

### ISSUE THREAD

**Issue by Thundros** [swift502/Sketchbook#7]
Hi @swift502! Just thought I'd let you know that for some reason I'm getting a huge lag around some of either the terrain & / or the objects in the scene. Can you please fix this? I will Beta test it for you!

Thank You!

**Comment by swift502** [comment]
Yeah I'm also getting low fps around the triangulated terrain when I spawn some balls with the "f" key.
It probably has to do with physics. I take this as a test map, so it just tells us that we shouldn't use trimesh terrain collisions in Cannon (the physics engine) unless absolutely necessary.

I'll let you know if / when I update this, but it might be some time. 🙂

**Comment by Thundros** [comment]
@swift502 : It actually did it without having to spawn any balls at all.

**Comment by radziksh** [comment]
@Thundros I had the same problem - in my case it was using of shadows. After I turned them off, `castShadow = false` the application began to work much faster.

**Comment by Thundros** [comment]
@radziksh Is there a way to use shadows without it affecting the FPS?

**Comment by Thundros** [comment]
Hello, @swift502  : Were you able to fix this? If not, can you fix this? Thanks!

**Comment by swift502** [comment]
@Thundros Not really, sorry.
I don't have performance issues so it's not a priority for me. We'd have to find the bottleneck first, and again, I'm not sure how to do that myself. It could be raycasting, it could be that I'm still using a naive physics broadphase (maybe simply switching to SAP would solve it?), I have no clue.

It's not a priority for me now. Unless you want to take a shot at identifying the bottleneck yourself, it might take a while before I focus on this issue. I currently prioritize working on new features, whenever I find the time to work on this at all. 🙁 

We can try making a SAP broadphase build to see if it improves the performance for you (If you're comfortable with cloning the repo and running the changes in a local server, I'd be happy to guide you through it)

**Comment by Thundros** [comment]
PLEASE fix the lag. It's driving me crazy. And I would really like to use some of the features in my own demo.

**Comment by swift502** [comment]
@Thundros I'm welcoming PRs. If you can fix the slowdown I'll be happy to accept your contribution.
I'm sorry, like I said, I'm not experiencing major slow downs. It's not a priority for me to fix something I can't even replicate.

**Comment by Thundros** [comment]
Why is the FPS only 30? It should be 60.

**Comment by swift502** [comment]
I get 55-60 fps

**Comment by Thundros** [comment]
I have an NVidia GeForce GTX 960M. I get 25 - 30.

**Comment by Thundros** [comment]
Hello?

**Comment by swift502** [comment]
Sir, I don't know what else to say.

1. I don't have performance issues
2. I don't want to spend time on fixing something that's not a problem for me
3. I don't know how to fix something I can't replicate

### You're free to fix the problem yourself. I'll be happy to accept your contribution.
No need to rely on me. That's the beauty of open source.

**Comment by Thundros** [comment]
So you don't want to devote time to all those people who have lower end graphics cards that can't afford top-notch computer tech, who actually would LOVE to test your software & possibly even use parts of it?

**Comment by swift502** [comment]
> So you don't want to devote time

I wish I could, but I can't. This is a hobby of mine, not my job.
And also, what do you want me to do? How do I fix a problem I can't replicate?
And how much FPS is enough FPS for you? 40? 50? 60?
If three.js is poorly optimised, do you expect me to go and fix three.js?
And how do you want me to believe that you'll ever

**Comment by swift502** [comment]
Sorry, you're free to fix the problem yourself. I'll be happy to accept your contribution.

Few things that might help me help us solve this:

- How much FPS do you get with shadows disabled?
- Can you make a video showcasing the problem, where and under which specific circumstances it occurs?
- Have you tried to identify the bottleneck? Is it rendering, physics or my logic?

**Comment by swift502** [comment]
Likely an issue with three.js, cannon.js, or just insufficient hardware capabilities.
Also, the number of FPS shouldn't influence the behaviour of my application. I spent a lot of time making sure of that.
Closing for now.

**Comment by swift502** [comment]
@Thundros One last shot in the dark, since I got no answers for my previous questions...

A friend of mine had an idea, that it might just be that you're not launching your browser with your graphics card, but rather the default integrated graphics of your CPU. I actually had to do this when I used to develop on a laptop. Can you try this and see if there's a difference?

![image](https://user-images.githubusercontent.com/24359130/71912982-c8069d00-3176-11ea-85c0-3883775582fb.png)

**Comment by FinalEra** [comment]
I'd like to chime in here, I get 60 fps (50 at the lowest when navigating the polygon mountain) on a 2 core celeron notebook with 2 gigs of ram.

On my 2011 iMac I get 60 fps solid throughout.

Similar results on my gtx 1060ti
